### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by felipenoris** [ungil/Bloomie.jl#1]
Hi! Is this package abandoned?

**Comment by ungil** [comment]
I do not have access to Bloomberg anymore. I don't know how much work would it take to make the library work again. The changes in Julia 1.0 (and in the libraries I used) will surely require some modifications.

There is a dependency on TimeSeriesIO, which doesn't seem to exist anymore (https://github.com/femtotrader/TimeSeriesIO.jl/issues/19), but it's just a couple of function calls and it should be easy to replace.

**Comment by felipenoris** [comment]
Ok. If you're unable to continue supporting this, please consider a transfer of ownership of this repository for JuliaFinance organization. I'll be glad to maintain this for you. I'll rewrite almost everything, but it would be cool to keep you on the history for your work.

**Comment by ungil** [comment]
Please feel free to fork the repository or use the code as you see fit if it's useful to you. I think the MIT license should be good enough to allow for reuse, let me know if there are any issues. The repository is not registered anywhere, there is no point in transfering it.

**Comment by felipenoris** [comment]
Ok, thanks!
